### GET request to example server
POST https://localhost:7109/api/inputs
Content-Type: application/json

{
    "appName": "TestApp",
    "data": "Sample input data"
}

###
POST https://localhost:7109/api/execution
Content-Type: application/json

{
  "inputids": [1,2],
  "name": "production"  
}

