### DoExecution
POST https://localhost:7109/api/executions
Content-Type: application/json

{
  "inputids": [1],
  "baseurl": "https://localhost:7220",
  "name": "experiment2"  
}

### AddInput
POST https://localhost:7109/api/input
Content-Type: application/json

< /Users/lucas/SolidGround/sample_ingress.json
